DEFAULTS = {
    "steam": False,
    "steam_window_title": "umamusume",
    "device_id": "emulator-5554",
    "difficulty_tm": "medium",
    "daily_sales_mode": "all",
    "shop_items": [],
    "use_parfait_TT": False,
    "use_parfait_daily_legends": False,
    "cm_extra_run": True,
    "make_your_own_team": False,
    "daily_race_difficulty": "very_hard",
    "daily_race_reward": "money",
    "daily_legends_champion": "Special Week",
}

DAILY_CHAMPIONS = [
    "El Condor Pasa",
    "Special Week",
    "Symboli Rudolf",
    "King Halo",
    "Taiki Shuttle",
    "Sakura Bakushin O",
    "Winning Ticket",
    "Vodka",
    "Tokai Teio",
    "Mayano Top Gun",
    "Mejiro McQueen",
    "TM Opera O",
    "Super Creek",
    "Mejiro Ryan",
    "Silence Suzuka",
    "Gold Ship",
    "Curren Chan",
    "Maruzensky",
    "Fuji Kiseki",
    "Mihono Bourbon",
    "Matikane Fukukitaru",
    "Seiun Sky",
    "Biwa Hayahide",
    "Air Groove",
    "Eishin Flash",
    "Agnes Digital",
    "Nice Nature",
    "Grass Wonder",
    "Oguri Cap",
]

SHOP_ITEMS = [
    "Star Piece",
    "Alarm Clock",
    "Pleasing Parfait",
    "Sprint Shoes",
    "Mile Shoes",
    "Medium Shoes",
    "Long Shoes",
    "Dirt Shoes",
    "Support Points",
    "Sash",
]
